apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  MYSQL_USER: {{ .Values.mysql.auth.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | quote }}
